# Dockerfile.dev

# Use the official .NET 9 SDK image for development
FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build

# Install necessary native build tools
RUN apt-get update \
    && apt-get install -y --no-install-recommends clang gcc libc6-dev libunwind-dev zlib1g-dev \
    && rm -rf /var/lib/apt/lists/*

# Set a working directory
WORKDIR /app

# Expose entrypoint as the dotnet CLI
ENTRYPOINT ["dotnet"]
